apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: admin1-streaming
spec:
  ingress:
    enabled: true
    security: none
  strategy: streaming
  collector:
    options:
      kafka:
        producer:
          #topic: ac1-jaeger-spans
          topic: jaeger-spans
          brokers: admin1-cluster-kafka-bootstrap.admin1-kafka.svc:9092
          batch-size: 128000
          batch-linger: 1s
          batch-max-messages: 100
  ingester:
    options:
      kafka:
        consumer:
          #topic: ac1-jaeger-spans
          topic: jaeger-spans
          brokers: admin1-cluster-kafka-bootstrap.admin1-kafka.svc:9092

      ingester:
        deadlockInterval: 0
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch.default.svc:9200
  #storage:
  #  type: elasticsearch
  #  elasticsearch:
  #    nodeCount: 1
  #    resources:
  #      requests:
  #        cpu: 200m
  #        memory: 1Gi
  #      limits:
  #        memory: 1Gi
